# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ads_mem_examples.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/ads_mem_examples.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1dprotos/ads_mem_examples.proto\"\x98\x06\n\x0e\x41\x64sMemExamples\x12\x15\n\x05\x64\x65\x62ug\x18\xe7\x07 \x01(\x08:\x05\x66\x61lse\x12\x17\n\nbatch_size\x18\x01 \x01(\x05:\x03\x31\x32\x38\x12 \n\x12\x66\x65\x61ture_dimensions\x18\x02 \x01(\x05:\x04\x31\x35\x33\x36\x12\x1e\n\x13max_stmts_per_image\x18\x03 \x01(\x05:\x01\x33\x12\x18\n\x0cmax_stmt_len\x18\x04 \x01(\x05:\x02\x32\x30\x12\x1d\n\x11number_of_regions\x18\x05 \x01(\x05:\x02\x31\x30\x12%\n\x16number_of_val_examples\x18\x06 \x01(\x05:\x05\x31\x30\x30\x30\x30\x12)\n\x1dnumber_of_val_stmts_per_image\x18\x07 \x01(\x05:\x02\x31\x35\x12\x1a\n\x12image_feature_path\x18\n \x01(\t\x12\x1b\n\x13region_feature_path\x18\x0b \x01(\t\x12\x1c\n\x14statement_vocab_path\x18\x0f \x01(\t\x12\x1c\n\x14statement_annot_path\x18\x10 \x01(\t\x12\x1b\n\x13\x64\x65nsecap_vocab_path\x18\x11 \x01(\t\x12\x1b\n\x13\x64\x65nsecap_annot_path\x18\x12 \x01(\t\x12\x19\n\x11symbol_annot_path\x18\x13 \x01(\t\x12\x1b\n\x13symbol_cluster_path\x18\x14 \x01(\t\x12!\n\x13shuffle_buffer_size\x18\x19 \x01(\x05:\x04\x31\x30\x30\x30\x12\x46\n\x12\x64\x61ta_provider_mode\x18\x1a \x01(\x0e\x32 .AdsMemExamples.DataProviderMode:\x08\x46ROM_CPU\x12#\n\x17max_densecaps_per_image\x18\x1e \x01(\x05:\x02\x31\x30\x12\x1c\n\x10max_densecap_len\x18\x1f \x01(\x05:\x02\x31\x30\x12\"\n\x13use_single_densecap\x18  \x01(\x08:\x05\x66\x61lse\x12 \n\x15max_symbols_per_image\x18! \x01(\x05:\x01\x35\".\n\x10\x44\x61taProviderMode\x12\x0c\n\x08\x46ROM_CPU\x10\x01\x12\x0c\n\x08\x46ROM_GPU\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_ADSMEMEXAMPLES_DATAPROVIDERMODE = _descriptor.EnumDescriptor(
  name='DataProviderMode',
  full_name='AdsMemExamples.DataProviderMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FROM_CPU', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FROM_GPU', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=780,
  serialized_end=826,
)
_sym_db.RegisterEnumDescriptor(_ADSMEMEXAMPLES_DATAPROVIDERMODE)


_ADSMEMEXAMPLES = _descriptor.Descriptor(
  name='AdsMemExamples',
  full_name='AdsMemExamples',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='debug', full_name='AdsMemExamples.debug', index=0,
      number=999, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='AdsMemExamples.batch_size', index=1,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=128,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feature_dimensions', full_name='AdsMemExamples.feature_dimensions', index=2,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1536,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_stmts_per_image', full_name='AdsMemExamples.max_stmts_per_image', index=3,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_stmt_len', full_name='AdsMemExamples.max_stmt_len', index=4,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=20,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='number_of_regions', full_name='AdsMemExamples.number_of_regions', index=5,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='number_of_val_examples', full_name='AdsMemExamples.number_of_val_examples', index=6,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=10000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='number_of_val_stmts_per_image', full_name='AdsMemExamples.number_of_val_stmts_per_image', index=7,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=15,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_feature_path', full_name='AdsMemExamples.image_feature_path', index=8,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='region_feature_path', full_name='AdsMemExamples.region_feature_path', index=9,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='statement_vocab_path', full_name='AdsMemExamples.statement_vocab_path', index=10,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='statement_annot_path', full_name='AdsMemExamples.statement_annot_path', index=11,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='densecap_vocab_path', full_name='AdsMemExamples.densecap_vocab_path', index=12,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='densecap_annot_path', full_name='AdsMemExamples.densecap_annot_path', index=13,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symbol_annot_path', full_name='AdsMemExamples.symbol_annot_path', index=14,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symbol_cluster_path', full_name='AdsMemExamples.symbol_cluster_path', index=15,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shuffle_buffer_size', full_name='AdsMemExamples.shuffle_buffer_size', index=16,
      number=25, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_provider_mode', full_name='AdsMemExamples.data_provider_mode', index=17,
      number=26, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_densecaps_per_image', full_name='AdsMemExamples.max_densecaps_per_image', index=18,
      number=30, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_densecap_len', full_name='AdsMemExamples.max_densecap_len', index=19,
      number=31, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_single_densecap', full_name='AdsMemExamples.use_single_densecap', index=20,
      number=32, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_symbols_per_image', full_name='AdsMemExamples.max_symbols_per_image', index=21,
      number=33, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ADSMEMEXAMPLES_DATAPROVIDERMODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=826,
)

_ADSMEMEXAMPLES.fields_by_name['data_provider_mode'].enum_type = _ADSMEMEXAMPLES_DATAPROVIDERMODE
_ADSMEMEXAMPLES_DATAPROVIDERMODE.containing_type = _ADSMEMEXAMPLES
DESCRIPTOR.message_types_by_name['AdsMemExamples'] = _ADSMEMEXAMPLES

AdsMemExamples = _reflection.GeneratedProtocolMessageType('AdsMemExamples', (_message.Message,), dict(
  DESCRIPTOR = _ADSMEMEXAMPLES,
  __module__ = 'protos.ads_mem_examples_pb2'
  # @@protoc_insertion_point(class_scope:AdsMemExamples)
  ))
_sym_db.RegisterMessage(AdsMemExamples)


# @@protoc_insertion_point(module_scope)
