# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/advise_model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import utils_pb2 as protos_dot_utils__pb2
from protos import text_encoders_pb2 as protos_dot_text__encoders__pb2
from protos import triplet_mining_pb2 as protos_dot_triplet__mining__pb2
from protos import mlp_pb2 as protos_dot_mlp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/advise_model.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x19protos/advise_model.proto\x1a\x12protos/utils.proto\x1a\x1aprotos/text_encoders.proto\x1a\x1bprotos/triplet_mining.proto\x1a\x10protos/mlp.proto\"\xcc\x07\n\x0b\x41\x44VISEModel\x12#\n\x15use_image_as_proposal\x18\x01 \x01(\x08:\x04true\x12!\n\rimage_encoder\x18\x02 \x01(\x0b\x32\n.FCEncoder\x12!\n\rimage_decoder\x18\x03 \x01(\x0b\x32\n.FCEncoder\x12\"\n\x0cstmt_encoder\x18\x04 \x01(\x0b\x32\x0c.TextEncoder\x12<\n\x0epooling_method\x18\x05 \x01(\x0e\x32\x1a.ADVISEModel.PoolingMethod:\x08\x41VG_POOL\x12-\n\x19image_attention_predictor\x18\x06 \x01(\x0b\x32\n.FCEncoder\x12&\n\x1bjoint_emb_dropout_keep_prob\x18\x10 \x01(\x02:\x01\x31\x12&\n\x0etriplet_mining\x18\x11 \x01(\x0b\x32\x0e.TripletMining\x12\x1b\n\x0etriplet_margin\x18\x12 \x01(\x02:\x03\x30.1\x12\"\n\x17\x61utoencoder_loss_weight\x18\x13 \x01(\x02:\x01\x31\x12\x1f\n\x14log_prob_loss_weight\x18\x14 \x01(\x02:\x01\x30\x12&\n\x17use_adversarial_dropout\x18\x15 \x01(\x08:\x05\x66\x61lse\x12\x1f\n\x14\x64\x65nsecap_loss_weight\x18\x1e \x01(\x02:\x01\x30\x12&\n\x10\x64\x65nsecap_encoder\x18\x1f \x01(\x0b\x32\x0c.TextEncoder\x12\x1d\n\x12symbol_loss_weight\x18  \x01(\x02:\x01\x30\x12$\n\x0esymbol_encoder\x18! \x01(\x0b\x32\x0c.TextEncoder\x12#\n\x14use_knowledge_branch\x18\" \x01(\x08:\x05\x66\x61lse\x12$\n\x11symbol_classifier\x18# \x01(\x0b\x32\t.MLPModel\x12V\n\x17knowledge_training_mode\x18$ \x01(\x0e\x32\".ADVISEModel.KnowledgeTrainingMode:\x11RESIDUAL_TRAINING\x12\x1b\n\x13symbol_cluster_path\x18% \x01(\t\"U\n\rPoolingMethod\x12\x0c\n\x08\x41VG_POOL\x10\x01\x12\x0c\n\x08\x41TT_POOL\x10\x02\x12\x13\n\x0f\x41TT_POOL_DS_SUM\x10\x03\x12\x13\n\x0f\x41TT_POOL_DS_MAX\x10\x04\"B\n\x15KnowledgeTrainingMode\x12\x12\n\x0eJOINT_TRAINING\x10\x01\x12\x15\n\x11RESIDUAL_TRAINING\x10\x02')
  ,
  dependencies=[protos_dot_utils__pb2.DESCRIPTOR,protos_dot_text__encoders__pb2.DESCRIPTOR,protos_dot_triplet__mining__pb2.DESCRIPTOR,protos_dot_mlp__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_ADVISEMODEL_POOLINGMETHOD = _descriptor.EnumDescriptor(
  name='PoolingMethod',
  full_name='ADVISEModel.PoolingMethod',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AVG_POOL', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ATT_POOL', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ATT_POOL_DS_SUM', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ATT_POOL_DS_MAX', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=944,
  serialized_end=1029,
)
_sym_db.RegisterEnumDescriptor(_ADVISEMODEL_POOLINGMETHOD)

_ADVISEMODEL_KNOWLEDGETRAININGMODE = _descriptor.EnumDescriptor(
  name='KnowledgeTrainingMode',
  full_name='ADVISEModel.KnowledgeTrainingMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='JOINT_TRAINING', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESIDUAL_TRAINING', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=1031,
  serialized_end=1097,
)
_sym_db.RegisterEnumDescriptor(_ADVISEMODEL_KNOWLEDGETRAININGMODE)


_ADVISEMODEL = _descriptor.Descriptor(
  name='ADVISEModel',
  full_name='ADVISEModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='use_image_as_proposal', full_name='ADVISEModel.use_image_as_proposal', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_encoder', full_name='ADVISEModel.image_encoder', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_decoder', full_name='ADVISEModel.image_decoder', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stmt_encoder', full_name='ADVISEModel.stmt_encoder', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pooling_method', full_name='ADVISEModel.pooling_method', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_attention_predictor', full_name='ADVISEModel.image_attention_predictor', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='joint_emb_dropout_keep_prob', full_name='ADVISEModel.joint_emb_dropout_keep_prob', index=6,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='triplet_mining', full_name='ADVISEModel.triplet_mining', index=7,
      number=17, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='triplet_margin', full_name='ADVISEModel.triplet_margin', index=8,
      number=18, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='autoencoder_loss_weight', full_name='ADVISEModel.autoencoder_loss_weight', index=9,
      number=19, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='log_prob_loss_weight', full_name='ADVISEModel.log_prob_loss_weight', index=10,
      number=20, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_adversarial_dropout', full_name='ADVISEModel.use_adversarial_dropout', index=11,
      number=21, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='densecap_loss_weight', full_name='ADVISEModel.densecap_loss_weight', index=12,
      number=30, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='densecap_encoder', full_name='ADVISEModel.densecap_encoder', index=13,
      number=31, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symbol_loss_weight', full_name='ADVISEModel.symbol_loss_weight', index=14,
      number=32, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symbol_encoder', full_name='ADVISEModel.symbol_encoder', index=15,
      number=33, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_knowledge_branch', full_name='ADVISEModel.use_knowledge_branch', index=16,
      number=34, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symbol_classifier', full_name='ADVISEModel.symbol_classifier', index=17,
      number=35, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='knowledge_training_mode', full_name='ADVISEModel.knowledge_training_mode', index=18,
      number=36, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symbol_cluster_path', full_name='ADVISEModel.symbol_cluster_path', index=19,
      number=37, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ADVISEMODEL_POOLINGMETHOD,
    _ADVISEMODEL_KNOWLEDGETRAININGMODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=1097,
)

_ADVISEMODEL.fields_by_name['image_encoder'].message_type = protos_dot_utils__pb2._FCENCODER
_ADVISEMODEL.fields_by_name['image_decoder'].message_type = protos_dot_utils__pb2._FCENCODER
_ADVISEMODEL.fields_by_name['stmt_encoder'].message_type = protos_dot_text__encoders__pb2._TEXTENCODER
_ADVISEMODEL.fields_by_name['pooling_method'].enum_type = _ADVISEMODEL_POOLINGMETHOD
_ADVISEMODEL.fields_by_name['image_attention_predictor'].message_type = protos_dot_utils__pb2._FCENCODER
_ADVISEMODEL.fields_by_name['triplet_mining'].message_type = protos_dot_triplet__mining__pb2._TRIPLETMINING
_ADVISEMODEL.fields_by_name['densecap_encoder'].message_type = protos_dot_text__encoders__pb2._TEXTENCODER
_ADVISEMODEL.fields_by_name['symbol_encoder'].message_type = protos_dot_text__encoders__pb2._TEXTENCODER
_ADVISEMODEL.fields_by_name['symbol_classifier'].message_type = protos_dot_mlp__pb2._MLPMODEL
_ADVISEMODEL.fields_by_name['knowledge_training_mode'].enum_type = _ADVISEMODEL_KNOWLEDGETRAININGMODE
_ADVISEMODEL_POOLINGMETHOD.containing_type = _ADVISEMODEL
_ADVISEMODEL_KNOWLEDGETRAININGMODE.containing_type = _ADVISEMODEL
DESCRIPTOR.message_types_by_name['ADVISEModel'] = _ADVISEMODEL

ADVISEModel = _reflection.GeneratedProtocolMessageType('ADVISEModel', (_message.Message,), dict(
  DESCRIPTOR = _ADVISEMODEL,
  __module__ = 'protos.advise_model_pb2'
  # @@protoc_insertion_point(class_scope:ADVISEModel)
  ))
_sym_db.RegisterMessage(ADVISEModel)


# @@protoc_insertion_point(module_scope)
