# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/image_stmt_model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import utils_pb2 as protos_dot_utils__pb2
from protos import text_encoders_pb2 as protos_dot_text__encoders__pb2
from protos import triplet_mining_pb2 as protos_dot_triplet__mining__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/image_stmt_model.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1dprotos/image_stmt_model.proto\x1a\x12protos/utils.proto\x1a\x1aprotos/text_encoders.proto\x1a\x1bprotos/triplet_mining.proto\"\xcf\x02\n\x0eImageStmtModel\x12!\n\rimage_encoder\x18\x01 \x01(\x0b\x32\n.FCEncoder\x12\"\n\x0cstmt_encoder\x18\x02 \x01(\x0b\x32\x0c.TextEncoder\x12@\n\x14image_pooling_method\x18\x04 \x01(\x0e\x32\x1d.ImageStmtModel.PoolingMethod:\x03NIL\x12&\n\x1bjoint_emb_dropout_keep_prob\x18\n \x01(\x02:\x01\x31\x12&\n\x0etriplet_mining\x18\x0b \x01(\x0b\x32\x0e.TripletMining\x12\x1b\n\x0etriplet_margin\x18\x0c \x01(\x02:\x03\x30.1\x12$\n\x15use_image_as_proposal\x18\x14 \x01(\x08:\x05\x66\x61lse\"!\n\rPoolingMethod\x12\x07\n\x03NIL\x10\x00\x12\x07\n\x03\x41VG\x10\x01')
  ,
  dependencies=[protos_dot_utils__pb2.DESCRIPTOR,protos_dot_text__encoders__pb2.DESCRIPTOR,protos_dot_triplet__mining__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_IMAGESTMTMODEL_POOLINGMETHOD = _descriptor.EnumDescriptor(
  name='PoolingMethod',
  full_name='ImageStmtModel.PoolingMethod',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NIL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AVG', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=413,
  serialized_end=446,
)
_sym_db.RegisterEnumDescriptor(_IMAGESTMTMODEL_POOLINGMETHOD)


_IMAGESTMTMODEL = _descriptor.Descriptor(
  name='ImageStmtModel',
  full_name='ImageStmtModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_encoder', full_name='ImageStmtModel.image_encoder', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stmt_encoder', full_name='ImageStmtModel.stmt_encoder', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_pooling_method', full_name='ImageStmtModel.image_pooling_method', index=2,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='joint_emb_dropout_keep_prob', full_name='ImageStmtModel.joint_emb_dropout_keep_prob', index=3,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='triplet_mining', full_name='ImageStmtModel.triplet_mining', index=4,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='triplet_margin', full_name='ImageStmtModel.triplet_margin', index=5,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_image_as_proposal', full_name='ImageStmtModel.use_image_as_proposal', index=6,
      number=20, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _IMAGESTMTMODEL_POOLINGMETHOD,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=446,
)

_IMAGESTMTMODEL.fields_by_name['image_encoder'].message_type = protos_dot_utils__pb2._FCENCODER
_IMAGESTMTMODEL.fields_by_name['stmt_encoder'].message_type = protos_dot_text__encoders__pb2._TEXTENCODER
_IMAGESTMTMODEL.fields_by_name['image_pooling_method'].enum_type = _IMAGESTMTMODEL_POOLINGMETHOD
_IMAGESTMTMODEL.fields_by_name['triplet_mining'].message_type = protos_dot_triplet__mining__pb2._TRIPLETMINING
_IMAGESTMTMODEL_POOLINGMETHOD.containing_type = _IMAGESTMTMODEL
DESCRIPTOR.message_types_by_name['ImageStmtModel'] = _IMAGESTMTMODEL

ImageStmtModel = _reflection.GeneratedProtocolMessageType('ImageStmtModel', (_message.Message,), dict(
  DESCRIPTOR = _IMAGESTMTMODEL,
  __module__ = 'protos.image_stmt_model_pb2'
  # @@protoc_insertion_point(class_scope:ImageStmtModel)
  ))
_sym_db.RegisterMessage(ImageStmtModel)


# @@protoc_insertion_point(module_scope)
