# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/mlp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from object_detection.protos import hyperparams_pb2 as object__detection_dot_protos_dot_hyperparams__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/mlp.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x10protos/mlp.proto\x1a)object_detection/protos/hyperparams.proto\"\xfb\x02\n\x08MLPModel\x12\x12\n\x05scope\x18\x01 \x01(\t:\x03mlp\x12\"\n\x17input_dropout_keep_prob\x18\x02 \x01(\x02:\x01\x31\x12@\n\x12hidden_hyperparams\x18\x03 \x01(\x0b\x32$.object_detection.protos.Hyperparams\x12\x18\n\rhidden_layers\x18\x04 \x01(\x05:\x01\x30\x12\x19\n\x0chidden_units\x18\x05 \x01(\x05:\x03\x32\x35\x36\x12#\n\x18hidden_dropout_keep_prob\x18\x06 \x01(\x02:\x01\x31\x12@\n\x12output_hyperparams\x18\x07 \x01(\x0b\x32$.object_detection.protos.Hyperparams\x12\x19\n\x0coutput_units\x18\x08 \x01(\x05:\x03\x32\x35\x36\x12#\n\x18output_dropout_keep_prob\x18\t \x01(\x02:\x01\x31\x12\x19\n\x0f\x63heckpoint_path\x18\n \x01(\t:\x00')
  ,
  dependencies=[object__detection_dot_protos_dot_hyperparams__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MLPMODEL = _descriptor.Descriptor(
  name='MLPModel',
  full_name='MLPModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scope', full_name='MLPModel.scope', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("mlp").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_dropout_keep_prob', full_name='MLPModel.input_dropout_keep_prob', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hidden_hyperparams', full_name='MLPModel.hidden_hyperparams', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hidden_layers', full_name='MLPModel.hidden_layers', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hidden_units', full_name='MLPModel.hidden_units', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=256,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hidden_dropout_keep_prob', full_name='MLPModel.hidden_dropout_keep_prob', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_hyperparams', full_name='MLPModel.output_hyperparams', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_units', full_name='MLPModel.output_units', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=256,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_dropout_keep_prob', full_name='MLPModel.output_dropout_keep_prob', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='checkpoint_path', full_name='MLPModel.checkpoint_path', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=443,
)

_MLPMODEL.fields_by_name['hidden_hyperparams'].message_type = object__detection_dot_protos_dot_hyperparams__pb2._HYPERPARAMS
_MLPMODEL.fields_by_name['output_hyperparams'].message_type = object__detection_dot_protos_dot_hyperparams__pb2._HYPERPARAMS
DESCRIPTOR.message_types_by_name['MLPModel'] = _MLPMODEL

MLPModel = _reflection.GeneratedProtocolMessageType('MLPModel', (_message.Message,), dict(
  DESCRIPTOR = _MLPMODEL,
  __module__ = 'protos.mlp_pb2'
  # @@protoc_insertion_point(class_scope:MLPModel)
  ))
_sym_db.RegisterMessage(MLPModel)


# @@protoc_insertion_point(module_scope)
