# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import vse_model_pb2 as protos_dot_vse__model__pb2
from protos import advise_model_pb2 as protos_dot_advise__model__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/model.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x12protos/model.proto\x1a\x16protos/vse_model.proto\x1a\x19protos/advise_model.proto\"V\n\x05Model\x12\x1e\n\tvse_model\x18\x01 \x01(\x0b\x32\t.VSEModelH\x00\x12$\n\x0c\x61\x64vise_model\x18\x02 \x01(\x0b\x32\x0c.ADVISEModelH\x00\x42\x07\n\x05model')
  ,
  dependencies=[protos_dot_vse__model__pb2.DESCRIPTOR,protos_dot_advise__model__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vse_model', full_name='Model.vse_model', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='advise_model', full_name='Model.advise_model', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='model', full_name='Model.model',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=73,
  serialized_end=159,
)

_MODEL.fields_by_name['vse_model'].message_type = protos_dot_vse__model__pb2._VSEMODEL
_MODEL.fields_by_name['advise_model'].message_type = protos_dot_advise__model__pb2._ADVISEMODEL
_MODEL.oneofs_by_name['model'].fields.append(
  _MODEL.fields_by_name['vse_model'])
_MODEL.fields_by_name['vse_model'].containing_oneof = _MODEL.oneofs_by_name['model']
_MODEL.oneofs_by_name['model'].fields.append(
  _MODEL.fields_by_name['advise_model'])
_MODEL.fields_by_name['advise_model'].containing_oneof = _MODEL.oneofs_by_name['model']
DESCRIPTOR.message_types_by_name['Model'] = _MODEL

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), dict(
  DESCRIPTOR = _MODEL,
  __module__ = 'protos.model_pb2'
  # @@protoc_insertion_point(class_scope:Model)
  ))
_sym_db.RegisterMessage(Model)


# @@protoc_insertion_point(module_scope)
