# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/pipeline.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import ads_mem_examples_pb2 as protos_dot_ads__mem__examples__pb2
from protos import model_pb2 as protos_dot_model__pb2
from protos import train_config_pb2 as protos_dot_train__config__pb2
from protos import eval_config_pb2 as protos_dot_eval__config__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/pipeline.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x15protos/pipeline.proto\x1a\x1dprotos/ads_mem_examples.proto\x1a\x12protos/model.proto\x1a\x19protos/train_config.proto\x1a\x18protos/eval_config.proto\"\x90\x01\n\x08Pipeline\x12\'\n\x0e\x65xample_reader\x18\x01 \x01(\x0b\x32\x0f.AdsMemExamples\x12\x15\n\x05model\x18\x02 \x01(\x0b\x32\x06.Model\x12\"\n\x0ctrain_config\x18\x03 \x01(\x0b\x32\x0c.TrainConfig\x12 \n\x0b\x65val_config\x18\x04 \x01(\x0b\x32\x0b.EvalConfig')
  ,
  dependencies=[protos_dot_ads__mem__examples__pb2.DESCRIPTOR,protos_dot_model__pb2.DESCRIPTOR,protos_dot_train__config__pb2.DESCRIPTOR,protos_dot_eval__config__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PIPELINE = _descriptor.Descriptor(
  name='Pipeline',
  full_name='Pipeline',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='example_reader', full_name='Pipeline.example_reader', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model', full_name='Pipeline.model', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='train_config', full_name='Pipeline.train_config', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eval_config', full_name='Pipeline.eval_config', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=274,
)

_PIPELINE.fields_by_name['example_reader'].message_type = protos_dot_ads__mem__examples__pb2._ADSMEMEXAMPLES
_PIPELINE.fields_by_name['model'].message_type = protos_dot_model__pb2._MODEL
_PIPELINE.fields_by_name['train_config'].message_type = protos_dot_train__config__pb2._TRAINCONFIG
_PIPELINE.fields_by_name['eval_config'].message_type = protos_dot_eval__config__pb2._EVALCONFIG
DESCRIPTOR.message_types_by_name['Pipeline'] = _PIPELINE

Pipeline = _reflection.GeneratedProtocolMessageType('Pipeline', (_message.Message,), dict(
  DESCRIPTOR = _PIPELINE,
  __module__ = 'protos.pipeline_pb2'
  # @@protoc_insertion_point(class_scope:Pipeline)
  ))
_sym_db.RegisterMessage(Pipeline)


# @@protoc_insertion_point(module_scope)
