# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/train_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/train_config.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x19protos/train_config.proto\"\x9e\x03\n\x0bTrainConfig\x12\x1d\n\toptimizer\x18\x01 \x01(\x0b\x32\n.Optimizer\x12\x15\n\rlearning_rate\x18\x02 \x01(\x02\x12\'\n\x19learning_rate_decay_steps\x18\x03 \x01(\x02:\x04\x32\x30\x30\x30\x12#\n\x18learning_rate_decay_rate\x18\x04 \x01(\x02:\x01\x31\x12%\n\x17learning_rate_staircase\x18\x05 \x01(\x08:\x04true\x12\x17\n\x0fnumber_of_steps\x18\x0b \x01(\x05\x12\x1d\n\x11log_every_n_steps\x18\x0c \x01(\x05:\x02\x31\x30\x12\x1f\n\x12save_interval_secs\x18\r \x01(\x05:\x03\x36\x30\x30\x12 \n\x13save_summaries_secs\x18\x0e \x01(\x05:\x03\x36\x30\x30\x12\x1d\n\x0emoving_average\x18\x0f \x01(\x08:\x05\x66\x61lse\x12\x30\n\x13gradient_multiplier\x18\x10 \x03(\x0b\x32\x13.GradientMultiplier\x12\x18\n\x10\x65xclude_variable\x18\x11 \x03(\t\"7\n\x12GradientMultiplier\x12\r\n\x05scope\x18\x01 \x01(\t\x12\x12\n\nmultiplier\x18\x02 \x01(\x02\"\x84\x01\n\tOptimizer\x12\x1e\n\x04\x61\x64\x61m\x18\x01 \x01(\x0b\x32\x0e.AdamOptimizerH\x00\x12$\n\x07\x61\x64\x61grad\x18\x02 \x01(\x0b\x32\x11.AdagradOptimizerH\x00\x12$\n\x07rmsprop\x18\x03 \x01(\x0b\x32\x11.RMSPropOptimizerH\x00\x42\x0b\n\toptimizer\"\x0f\n\rAdamOptimizer\"\x12\n\x10\x41\x64\x61gradOptimizer\";\n\x10RMSPropOptimizer\x12\x12\n\x05\x64\x65\x63\x61y\x18\x01 \x01(\x02:\x03\x30.9\x12\x13\n\x08momentum\x18\x02 \x01(\x02:\x01\x30')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TRAINCONFIG = _descriptor.Descriptor(
  name='TrainConfig',
  full_name='TrainConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='optimizer', full_name='TrainConfig.optimizer', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='learning_rate', full_name='TrainConfig.learning_rate', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='learning_rate_decay_steps', full_name='TrainConfig.learning_rate_decay_steps', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(2000),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='learning_rate_decay_rate', full_name='TrainConfig.learning_rate_decay_rate', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='learning_rate_staircase', full_name='TrainConfig.learning_rate_staircase', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='number_of_steps', full_name='TrainConfig.number_of_steps', index=5,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='log_every_n_steps', full_name='TrainConfig.log_every_n_steps', index=6,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='save_interval_secs', full_name='TrainConfig.save_interval_secs', index=7,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=600,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='save_summaries_secs', full_name='TrainConfig.save_summaries_secs', index=8,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=600,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='moving_average', full_name='TrainConfig.moving_average', index=9,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gradient_multiplier', full_name='TrainConfig.gradient_multiplier', index=10,
      number=16, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exclude_variable', full_name='TrainConfig.exclude_variable', index=11,
      number=17, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=444,
)


_GRADIENTMULTIPLIER = _descriptor.Descriptor(
  name='GradientMultiplier',
  full_name='GradientMultiplier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scope', full_name='GradientMultiplier.scope', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='multiplier', full_name='GradientMultiplier.multiplier', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=501,
)


_OPTIMIZER = _descriptor.Descriptor(
  name='Optimizer',
  full_name='Optimizer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='adam', full_name='Optimizer.adam', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adagrad', full_name='Optimizer.adagrad', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rmsprop', full_name='Optimizer.rmsprop', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='optimizer', full_name='Optimizer.optimizer',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=504,
  serialized_end=636,
)


_ADAMOPTIMIZER = _descriptor.Descriptor(
  name='AdamOptimizer',
  full_name='AdamOptimizer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=638,
  serialized_end=653,
)


_ADAGRADOPTIMIZER = _descriptor.Descriptor(
  name='AdagradOptimizer',
  full_name='AdagradOptimizer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=655,
  serialized_end=673,
)


_RMSPROPOPTIMIZER = _descriptor.Descriptor(
  name='RMSPropOptimizer',
  full_name='RMSPropOptimizer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='decay', full_name='RMSPropOptimizer.decay', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.9),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='momentum', full_name='RMSPropOptimizer.momentum', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=675,
  serialized_end=734,
)

_TRAINCONFIG.fields_by_name['optimizer'].message_type = _OPTIMIZER
_TRAINCONFIG.fields_by_name['gradient_multiplier'].message_type = _GRADIENTMULTIPLIER
_OPTIMIZER.fields_by_name['adam'].message_type = _ADAMOPTIMIZER
_OPTIMIZER.fields_by_name['adagrad'].message_type = _ADAGRADOPTIMIZER
_OPTIMIZER.fields_by_name['rmsprop'].message_type = _RMSPROPOPTIMIZER
_OPTIMIZER.oneofs_by_name['optimizer'].fields.append(
  _OPTIMIZER.fields_by_name['adam'])
_OPTIMIZER.fields_by_name['adam'].containing_oneof = _OPTIMIZER.oneofs_by_name['optimizer']
_OPTIMIZER.oneofs_by_name['optimizer'].fields.append(
  _OPTIMIZER.fields_by_name['adagrad'])
_OPTIMIZER.fields_by_name['adagrad'].containing_oneof = _OPTIMIZER.oneofs_by_name['optimizer']
_OPTIMIZER.oneofs_by_name['optimizer'].fields.append(
  _OPTIMIZER.fields_by_name['rmsprop'])
_OPTIMIZER.fields_by_name['rmsprop'].containing_oneof = _OPTIMIZER.oneofs_by_name['optimizer']
DESCRIPTOR.message_types_by_name['TrainConfig'] = _TRAINCONFIG
DESCRIPTOR.message_types_by_name['GradientMultiplier'] = _GRADIENTMULTIPLIER
DESCRIPTOR.message_types_by_name['Optimizer'] = _OPTIMIZER
DESCRIPTOR.message_types_by_name['AdamOptimizer'] = _ADAMOPTIMIZER
DESCRIPTOR.message_types_by_name['AdagradOptimizer'] = _ADAGRADOPTIMIZER
DESCRIPTOR.message_types_by_name['RMSPropOptimizer'] = _RMSPROPOPTIMIZER

TrainConfig = _reflection.GeneratedProtocolMessageType('TrainConfig', (_message.Message,), dict(
  DESCRIPTOR = _TRAINCONFIG,
  __module__ = 'protos.train_config_pb2'
  # @@protoc_insertion_point(class_scope:TrainConfig)
  ))
_sym_db.RegisterMessage(TrainConfig)

GradientMultiplier = _reflection.GeneratedProtocolMessageType('GradientMultiplier', (_message.Message,), dict(
  DESCRIPTOR = _GRADIENTMULTIPLIER,
  __module__ = 'protos.train_config_pb2'
  # @@protoc_insertion_point(class_scope:GradientMultiplier)
  ))
_sym_db.RegisterMessage(GradientMultiplier)

Optimizer = _reflection.GeneratedProtocolMessageType('Optimizer', (_message.Message,), dict(
  DESCRIPTOR = _OPTIMIZER,
  __module__ = 'protos.train_config_pb2'
  # @@protoc_insertion_point(class_scope:Optimizer)
  ))
_sym_db.RegisterMessage(Optimizer)

AdamOptimizer = _reflection.GeneratedProtocolMessageType('AdamOptimizer', (_message.Message,), dict(
  DESCRIPTOR = _ADAMOPTIMIZER,
  __module__ = 'protos.train_config_pb2'
  # @@protoc_insertion_point(class_scope:AdamOptimizer)
  ))
_sym_db.RegisterMessage(AdamOptimizer)

AdagradOptimizer = _reflection.GeneratedProtocolMessageType('AdagradOptimizer', (_message.Message,), dict(
  DESCRIPTOR = _ADAGRADOPTIMIZER,
  __module__ = 'protos.train_config_pb2'
  # @@protoc_insertion_point(class_scope:AdagradOptimizer)
  ))
_sym_db.RegisterMessage(AdagradOptimizer)

RMSPropOptimizer = _reflection.GeneratedProtocolMessageType('RMSPropOptimizer', (_message.Message,), dict(
  DESCRIPTOR = _RMSPROPOPTIMIZER,
  __module__ = 'protos.train_config_pb2'
  # @@protoc_insertion_point(class_scope:RMSPropOptimizer)
  ))
_sym_db.RegisterMessage(RMSPropOptimizer)


# @@protoc_insertion_point(module_scope)
