# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/triplet_mining.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/triplet_mining.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1bprotos/triplet_mining.proto\"\xac\x01\n\rTripletMining\x12\x1c\n\x08mine_all\x18\x01 \x01(\x0b\x32\x08.MineAllH\x00\x12\x1e\n\tmine_hard\x18\x02 \x01(\x0b\x32\t.MineHardH\x00\x12\'\n\x0emine_semi_hard\x18\x03 \x01(\x0b\x32\r.MineSemiHardH\x00\x12\"\n\x0bmine_random\x18\x04 \x01(\x0b\x32\x0b.MineRandomH\x00\x42\x10\n\x0etriplet_mining\"\t\n\x07MineAll\"\x0e\n\x0cMineSemiHard\"\x1c\n\x08MineHard\x12\x10\n\x05top_k\x18\x01 \x01(\x05:\x01\x31\"-\n\nMineRandom\x12\x1f\n\x14negatives_per_anchor\x18\x01 \x01(\x05:\x01\x31')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TRIPLETMINING = _descriptor.Descriptor(
  name='TripletMining',
  full_name='TripletMining',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mine_all', full_name='TripletMining.mine_all', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mine_hard', full_name='TripletMining.mine_hard', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mine_semi_hard', full_name='TripletMining.mine_semi_hard', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mine_random', full_name='TripletMining.mine_random', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='triplet_mining', full_name='TripletMining.triplet_mining',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=32,
  serialized_end=204,
)


_MINEALL = _descriptor.Descriptor(
  name='MineAll',
  full_name='MineAll',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=215,
)


_MINESEMIHARD = _descriptor.Descriptor(
  name='MineSemiHard',
  full_name='MineSemiHard',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=231,
)


_MINEHARD = _descriptor.Descriptor(
  name='MineHard',
  full_name='MineHard',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='top_k', full_name='MineHard.top_k', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=261,
)


_MINERANDOM = _descriptor.Descriptor(
  name='MineRandom',
  full_name='MineRandom',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='negatives_per_anchor', full_name='MineRandom.negatives_per_anchor', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=308,
)

_TRIPLETMINING.fields_by_name['mine_all'].message_type = _MINEALL
_TRIPLETMINING.fields_by_name['mine_hard'].message_type = _MINEHARD
_TRIPLETMINING.fields_by_name['mine_semi_hard'].message_type = _MINESEMIHARD
_TRIPLETMINING.fields_by_name['mine_random'].message_type = _MINERANDOM
_TRIPLETMINING.oneofs_by_name['triplet_mining'].fields.append(
  _TRIPLETMINING.fields_by_name['mine_all'])
_TRIPLETMINING.fields_by_name['mine_all'].containing_oneof = _TRIPLETMINING.oneofs_by_name['triplet_mining']
_TRIPLETMINING.oneofs_by_name['triplet_mining'].fields.append(
  _TRIPLETMINING.fields_by_name['mine_hard'])
_TRIPLETMINING.fields_by_name['mine_hard'].containing_oneof = _TRIPLETMINING.oneofs_by_name['triplet_mining']
_TRIPLETMINING.oneofs_by_name['triplet_mining'].fields.append(
  _TRIPLETMINING.fields_by_name['mine_semi_hard'])
_TRIPLETMINING.fields_by_name['mine_semi_hard'].containing_oneof = _TRIPLETMINING.oneofs_by_name['triplet_mining']
_TRIPLETMINING.oneofs_by_name['triplet_mining'].fields.append(
  _TRIPLETMINING.fields_by_name['mine_random'])
_TRIPLETMINING.fields_by_name['mine_random'].containing_oneof = _TRIPLETMINING.oneofs_by_name['triplet_mining']
DESCRIPTOR.message_types_by_name['TripletMining'] = _TRIPLETMINING
DESCRIPTOR.message_types_by_name['MineAll'] = _MINEALL
DESCRIPTOR.message_types_by_name['MineSemiHard'] = _MINESEMIHARD
DESCRIPTOR.message_types_by_name['MineHard'] = _MINEHARD
DESCRIPTOR.message_types_by_name['MineRandom'] = _MINERANDOM

TripletMining = _reflection.GeneratedProtocolMessageType('TripletMining', (_message.Message,), dict(
  DESCRIPTOR = _TRIPLETMINING,
  __module__ = 'protos.triplet_mining_pb2'
  # @@protoc_insertion_point(class_scope:TripletMining)
  ))
_sym_db.RegisterMessage(TripletMining)

MineAll = _reflection.GeneratedProtocolMessageType('MineAll', (_message.Message,), dict(
  DESCRIPTOR = _MINEALL,
  __module__ = 'protos.triplet_mining_pb2'
  # @@protoc_insertion_point(class_scope:MineAll)
  ))
_sym_db.RegisterMessage(MineAll)

MineSemiHard = _reflection.GeneratedProtocolMessageType('MineSemiHard', (_message.Message,), dict(
  DESCRIPTOR = _MINESEMIHARD,
  __module__ = 'protos.triplet_mining_pb2'
  # @@protoc_insertion_point(class_scope:MineSemiHard)
  ))
_sym_db.RegisterMessage(MineSemiHard)

MineHard = _reflection.GeneratedProtocolMessageType('MineHard', (_message.Message,), dict(
  DESCRIPTOR = _MINEHARD,
  __module__ = 'protos.triplet_mining_pb2'
  # @@protoc_insertion_point(class_scope:MineHard)
  ))
_sym_db.RegisterMessage(MineHard)

MineRandom = _reflection.GeneratedProtocolMessageType('MineRandom', (_message.Message,), dict(
  DESCRIPTOR = _MINERANDOM,
  __module__ = 'protos.triplet_mining_pb2'
  # @@protoc_insertion_point(class_scope:MineRandom)
  ))
_sym_db.RegisterMessage(MineRandom)


# @@protoc_insertion_point(module_scope)
