# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/vse_model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import utils_pb2 as protos_dot_utils__pb2
from protos import text_encoders_pb2 as protos_dot_text__encoders__pb2
from protos import triplet_mining_pb2 as protos_dot_triplet__mining__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/vse_model.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x16protos/vse_model.proto\x1a\x12protos/utils.proto\x1a\x1aprotos/text_encoders.proto\x1a\x1bprotos/triplet_mining.proto\"\xbe\x01\n\x08VSEModel\x12!\n\rimage_encoder\x18\x01 \x01(\x0b\x32\n.FCEncoder\x12\"\n\x0cstmt_encoder\x18\x02 \x01(\x0b\x32\x0c.TextEncoder\x12&\n\x1bjoint_emb_dropout_keep_prob\x18\n \x01(\x02:\x01\x31\x12&\n\x0etriplet_mining\x18\x0b \x01(\x0b\x32\x0e.TripletMining\x12\x1b\n\x0etriplet_margin\x18\x0c \x01(\x02:\x03\x30.2')
  ,
  dependencies=[protos_dot_utils__pb2.DESCRIPTOR,protos_dot_text__encoders__pb2.DESCRIPTOR,protos_dot_triplet__mining__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_VSEMODEL = _descriptor.Descriptor(
  name='VSEModel',
  full_name='VSEModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_encoder', full_name='VSEModel.image_encoder', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stmt_encoder', full_name='VSEModel.stmt_encoder', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='joint_emb_dropout_keep_prob', full_name='VSEModel.joint_emb_dropout_keep_prob', index=2,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='triplet_mining', full_name='VSEModel.triplet_mining', index=3,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='triplet_margin', full_name='VSEModel.triplet_margin', index=4,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=294,
)

_VSEMODEL.fields_by_name['image_encoder'].message_type = protos_dot_utils__pb2._FCENCODER
_VSEMODEL.fields_by_name['stmt_encoder'].message_type = protos_dot_text__encoders__pb2._TEXTENCODER
_VSEMODEL.fields_by_name['triplet_mining'].message_type = protos_dot_triplet__mining__pb2._TRIPLETMINING
DESCRIPTOR.message_types_by_name['VSEModel'] = _VSEMODEL

VSEModel = _reflection.GeneratedProtocolMessageType('VSEModel', (_message.Message,), dict(
  DESCRIPTOR = _VSEMODEL,
  __module__ = 'protos.vse_model_pb2'
  # @@protoc_insertion_point(class_scope:VSEModel)
  ))
_sym_db.RegisterMessage(VSEModel)


# @@protoc_insertion_point(module_scope)
